### ISSUE TITLE
An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by poumason** [PeterWaher/IoTGateway#4]
https://github.com/PeterWaher/IoTGateway/blob/master/Networking/Waher.Networking.MQTT/MqttClient.cs#L408

I try use UWP version to connect MQTT server, but still not be connected.
I always receive the exception.
I don't know what happened.

**Comment by PeterWaher** [comment]
The server closed the connection. Possibly because the client was not authenticated. You need to troubleshoot the communication to see what happens. You can either use an external tool (WireShark), or internal tool (sniffers). Sniffers allow you to troubleshoot encrypted communication on your end.

There are working examples here:
https://github.com/PeterWaher/MIoT

You can test them against the MQTT broker at iot.eclipse.org.

**Comment by poumason** [comment]
Thank you. I try it.
